name: flutter_bird
description: A Flappy Bird clone making use of NFTs
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/Tonnanto/flutter-bird

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^5.0.1 
  shared_preferences_android: ^2.0.0
  url_launcher_android: ^6.0.0
  flutter_dotenv: ^5.1.0

  web3dart: 2.7.3
  walletconnect_flutter_v2: ^2.2.1
  eth_sig_util: 0.0.9
  nonce: 1.2.0
  url_launcher: 6.3.0
  provider: 6.0.3
  qr_flutter: 4.1.0
  http: 1.2.0
  flutter_line_liff: ^0.0.3

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  shared_preferences: 2.2.3
  build_runner: 2.4.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#40C4FF"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - env
  fonts:
    - family: flappy
      fonts:
        - asset: fonts/FlappyBirdRegular-9Pq0.ttf
